[package]
name = "aoc-profile-tree"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "aoc-tree"
path = "src/main.rs"

[dependencies]
axum = { version = "0.8.8", features = ["macros"] }
chrono = "0.4.42"
clap = { version = "4.5.54", features = ["derive", "env"] }
reqwest = { version = "0.13.1", features = ["blocking"] }
scraper = "0.25.0"
shuttle-axum = "0.57.0"
shuttle-runtime = "0.57.0"
thiserror = "2.0.17"
tokio = { version = "1.49.0", features = ["full"] }
